/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projvirtual2_hospital;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;

/**
 *
 * @author andre
 */
public class HospitaisJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HospitaisJFrame
     */
    private DefaultListModel<Hospital> listaVisual;
    
    public HospitaisJFrame() {
        listaVisual = new DefaultListModel<Hospital>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeHospitaljTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        leitosTotaisjTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        leitosOcupadojTextField3 = new javax.swing.JTextField();
        InserejButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaHospitaljList1 = new javax.swing.JList<Hospital>();
        CalculajButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TOTALjLabel5 = new javax.swing.JLabel();
        RemovejButton1 = new javax.swing.JButton();
        AlterajButton2 = new javax.swing.JButton();
        LimpajButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Hospital");

        nomeHospitaljTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Leitos");

        leitosTotaisjTextField2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Ocupados");

        leitosOcupadojTextField3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        InserejButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        InserejButton1.setText("INSERE");

        listaHospitaljList1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        listaHospitaljList1.setModel(listaVisual);
        jScrollPane1.setViewportView(listaHospitaljList1);

        CalculajButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CalculajButton1.setText("Calcula TOTAL Leitos Livres");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("TOTAL");

        TOTALjLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        TOTALjLabel5.setText("_______");

        RemovejButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RemovejButton1.setText("REMOVE");

        AlterajButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        AlterajButton2.setText("ALTERA");

        LimpajButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LimpajButton3.setText("LIMPA LISTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeHospitaljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(leitosOcupadojTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                        .addComponent(leitosTotaisjTextField2, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(InserejButton1)
                                .addGap(33, 33, 33)
                                .addComponent(RemovejButton1)
                                .addGap(41, 41, 41)
                                .addComponent(AlterajButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CalculajButton1)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addComponent(TOTALjLabel5))
                    .addComponent(LimpajButton3))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomeHospitaljTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(leitosTotaisjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(leitosOcupadojTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InserejButton1)
                            .addComponent(RemovejButton1)
                            .addComponent(AlterajButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(LimpajButton3)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TOTALjLabel5))
                    .addComponent(CalculajButton1))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public Hospital obterHospital(){
        String nome       = nomeHospitaljTextField1.getText();
        int    totLeitos  = Integer.parseInt(leitosTotaisjTextField2.getText())  ;
        int    leitoOc    = Integer.parseInt(leitosOcupadojTextField3.getText());       
        Hospital h = new Hospital(nome, totLeitos, leitoOc);        
        return h;
    }
    public void addInsereListener(ActionListener l){
        InserejButton1.addActionListener(l);        
    }
    public void colocaManipuladorDeTotal(ActionListener l){
        CalculajButton1.addActionListener(l);
    }
    public void colocaLimpaManip(ActionListener l){
        LimpajButton3.addActionListener(l);
    }
    
    public void colocaRemoveManip(ActionListener l){
        RemovejButton1.addActionListener(l);
    }
    public void colocaAlteraManip(ActionListener l){
        AlterajButton2.addActionListener(l);
    }
    
    public void mostraLista(ArrayList<Hospital> lista){
        limpaListaVisual();
        Iterator<Hospital> it = lista.iterator();
        while(it.hasNext()){
            // total = it.next().leitosDisponiveis();--> Alternativa            
            Hospital h = it.next();
            insereHospitalLista(h);
        }       
    }
    
    public void limpaListaVisual(){
        listaVisual.clear();
    }
    
    public void insereHospitalLista(Hospital h){
        listaVisual.addElement(h);
    }
    
    public void insereTotalLeitos(int total){
        //TOTALjLabel5.setText(Integer.toString(total));
        TOTALjLabel5.setText("" + total);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterajButton2;
    private javax.swing.JButton CalculajButton1;
    private javax.swing.JButton InserejButton1;
    private javax.swing.JButton LimpajButton3;
    private javax.swing.JButton RemovejButton1;
    private javax.swing.JLabel TOTALjLabel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField leitosOcupadojTextField3;
    private javax.swing.JTextField leitosTotaisjTextField2;
    private javax.swing.JList<Hospital> listaHospitaljList1;
    private javax.swing.JTextField nomeHospitaljTextField1;
    // End of variables declaration//GEN-END:variables
}
